FROM python:3.9-slim

WORKDIR /app

# Copier les fichiers de dépendances
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source
COPY config/ ./config/
COPY utils/ ./utils/
COPY src/result_consumer.py ./

# Commande de démarrage
CMD ["python", "result_consumer.py", "--verbose"] 